### ISSUE TITLE
Improvements and Fix Request [iOS build]

### ISSUE THREAD

**Issue by bachig26** [femalemonkeyman/anicross#2]
I used the iOS build just now and found some issues with it. I'm listing below, please have a look at them.

1. ![image](https://user-images.githubusercontent.com/96393348/219883866-e326ae25-5b3b-4ea8-b4c3-0dc0cc8e68a7.jpeg)

I'd hope to see a icon for the app in future.

2. Can't exit from the fullscreen, 
I have attached a clip here, not sure if you can see it clearly but the fullscreen toggle button doesn't work and there are no ways to go back to episodes list or homepage without restarting the app.
https://user-images.githubusercontent.com/96393348/219883994-25268d72-b158-41e4-992a-500d785f8b1e.MOV

I would like to see these comes to life in next build if possible the fullscreen exit fix 1st.

Thanks, app works nice otherwise. Will try more and see it.✨

**Comment by bachig26** [comment]
I also thought if I rotate the phone, it'll change the orientation of the video player but there was no change.

**Comment by femalemonkeyman** [comment]
Right, iphone has no back button. The player itself is a package and the controls are part of that package. Android you can just hit the back button and desktop I made the controls myself

**Comment by femalemonkeyman** [comment]
That should solve not being able to exit. I added a backbutton and that does work on the android build but you'll have to let me know

**Comment by bachig26** [comment]
> That should solve not being able to exit. I added a backbutton and that does work on the android build but you'll have to let me know

the back button works. 👍
#### 1. from my iPhone SE 1st Gen:

https://user-images.githubusercontent.com/96393348/219968715-762ad3f8-629e-4129-9f60-48170d6361e2.mp4

#### 2. from my iPhone SE 3st Gen:

https://user-images.githubusercontent.com/96393348/219968989-6450513a-026f-4fbf-b740-e1b3597d3bb2.mp4

few things I noticed and as you can see in the clips,

1. the content icons are too small.

2. the back button is not consistent with others, and the other buttons in the video player has the dark background. If possible, I would like to see it in translucent similar to the apple AVPlayer buttons.


also the settings button in the search doesn't work, I don't if it's a bug or still in work?

**Comment by femalemonkeyman** [comment]
Oh whoops, changes i made to the grid got pushed there because i wasn't checking for ios. In terms of the player design i might look into that but i thought better player had the silverish button styles. The settings is a page I haven't even put thought into at the moment just because the biggest concern i have is general functionality and laying foundation of something before i improve design and allow that design to be changed

**Comment by bachig26** [comment]
> Oh whoops, changes i made to the grid got pushed there because i wasn't checking for ios. 

okay 👍

> In terms of the player design i might look into that but i thought better player had the silverish button styles. 

silverish button styles as how the back button is looks good, but there are not consistent with others, that's a thing I wanted to mention earlier too. if other buttons are also similar to back button then it'll be also cool to see. either style is cool but less opaque is better.

> The settings is a page I haven't even put thought into at the moment just because the biggest concern i have is general functionality and laying foundation of something before i improve design and allow that design to be changed

i can understand that, and also I was mentioning about the settings icon in the search bar, as you can see in the clips above. that setting type icon doesn't work when clicked to check what that is.

**Comment by femalemonkeyman** [comment]
I'll have to figure out how to change the player plugin to just use material on iOS. 

The settings icon in the search bar will be settings for each section

**Comment by femalemonkeyman** [comment]
I should potentially have fixed the grid issue. I'm putting in some new designs and features though so things will still be a little weird or wonky
